duskfall_monsters = [
    "Aarakocra",
    "Aboleth",
    "Adult Gold Dragon",
    "Air Elemental",
    "Allosaurus",
    "Ancient Bronze Dragon",
    "Ancient Gold Dragon",
    "Ancient Green Dragon",
    "Ancient Red Dragon",
    "Ancient White Dragon",
    "Androsphinx",
    "Ankheg",
    "Ankylosaurus",
    "Ape",
    "Atropal",
    "Baboon",
    "Barghest",
    "Basilisk",
    "Behir",
    "Beholder Zombie",
    "Blood Hawk",
    "Bodak",
    "Bone Naga",
    "Boneclaw",
    "Boar",
    "Brass Dragon Adult",
    "Brass Dragon Ancient",
    "Brass Dragon Wyrmling",
    "Brass Dragon Young",
    "Brontosaurus",
    "Bugbear",
    "Cadaver Collector",
    "Camel",
    "Centaur",
    "Chimera",
    "Cloud Giant",
    "Corpse Flower",
    "Couatl",
    "Crab",
    "Cranium Rat",
    "Death Kiss",
    "Death Tyrant (Beholder)",
    "Deer",
    "Deinonychus",
    "Dire Wolf",
    "Dolphin",
    "Doppelganger",
    "Dragon Turtle",
    "Dracolich",
    "Dust Mephit",
    "Eagle",
    "Efreeti",
    "Elder Tempest",
    "Elkhorn Dinosaur",
    "Empyrean",
    "Ettercap",
    "Ettin",
    "Fenrir",
    "Fire Giant Dreadnought",
    "Fire Snake",
    "Flameskull",
    "Flind",
    "Frost Giant",
    "Froghemoth",
    "Galeb Duhr",
    "Gargoyle",
    "Ghast",
    "Ghost",
    "Ghoul",
    "Giant Crab",
    "Giant Eagle",
    "Giant Lizard",
    "Giant Octopus",
    "Giant Poisonous Snake",
    "Giant Rat",
    "Giant Sea Horse",
    "Giant Shark",
    "Giant Spider",
    "Giant Squid",
    "Girallon",
    "Gnoll",
    "Gnoll Fang of Yeenoghu",
    "Gnoll Pack Lord",
    "Goat",
    "Goblin",
    "Gorgon",
    "Griffon",
    "Gynosphinx",
    "Hadrosaurus",
    "Hawk",
    "Hippogriff",
    "Hobgoblin",
    "Jackal",
    "Killer Whale",
    "Kobold",
    "Kobold Dragonshield",
    "Kobold Inventor",
    "Kobold Scale Sorcerer",
    "Kraken",
    "Kraken Priest",
    "Lamia",
    "Leviathan",
    "Lich",
    "Lizardfolk Shaman",
    "Lolth (Demon Queen of Spiders)",
    "Manticore",
    "Marid",
    "Merfolk",
    "Merrow",
    "Mimic",
    "Mummy",
    "Mummy Lord",
    "Nightwalker",
    "Octopus",
    "Ogre",
    "Ogre Zombie",
    "Olhydra",
    "Oni",
    "Orc",
    "Orc Blade of Ilneval",
    "Orc Claw of Luthic",
    "Orc Eye of Gruumsh",
    "Orc Red Fang of Shargaas",
    "Orc War Chief",
    "Orcus",
    "Otyugh",
    "Pegasus",
    "Phase Spider",
    "Phoenix",
    "Plesiosaurus",
    "Pteranodon",
    "Rat",
    "Reef Fish",
    "Reef Shark",
    "Revenant",
    "Roc",
    "Sahuagin",
    "Salamander",
    "Sand Silhouette",
    "Scarecrow",
    "Scorpion",
    "Sea Hag",
    "Sea Lion",
    "Shadow",
    "Skeleton",
    "Skull Lord",
    "Spider",
    "Specter",
    "Stirge",
    "Stone Giant",
    "Storm Giant",
    "Tarrasque",
    "Thunderbird",
    "Treant",
    "Triceratops",
    "Troll",
    "Tromokratis",
    "Tyrannosaurus Rex",
    "Unicorn",
    "Vampire",
    "Vampire Lord",
    "Vampire Spawn",
    "Vampire Spellcaster",
    "Vampire Warrior",
    "Vulture",
    "Water Elemental",
    "Wererat",
    "Werewolf",
    "Wight",
    "Wild Horse",
    "Winter Wolf",
    "Wolf",
    "Worg",
    "Wraith",
    "Wyvern",
    "Yuan-ti Abomination",
    "Yuan-ti Anathema",
    "Yuan-ti Malison",
    "Yuan-ti Pureblood",
    "Zaratan",
    "Zombie"
]
